version: '3'

services:
  db:
    image: postgres
    #restart: always
    #environment:
      #POSTGRES_DB: "uocsecret_db"
      #POSTGRES_USER: "uocsecret_admin"
      #POSTGRES_PASSWORD: "uocsecret_password"
  web:
    build: .
    volumes:
      - .:/uocweb
    command: bash -c "python uocsecrets/manage.py makemigrations forum &&
                      python uocsecrets/manage.py makemigrations &&
                      python uocsecrets/manage.py migrate &&
                      python uocsecrets/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db