# Generated by Django 2.1.1 on 2018-09-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_pk',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
