# Generated by Django 2.1 on 2018-09-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='name',
        ),
    ]
