# Generated by Django 2.1 on 2018-09-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180901_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
