# Generated by Django 2.1 on 2018-09-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20180911_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='author',
        ),
    ]
