# Generated by Django 2.2 on 2019-04-05 16:12

import django.core.validators
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180925_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.rand_path_filename, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
